
services:
  server:
    image: ghcr.io/jcollingwood/jc-kotlin-template:0d010e5b96bfaff9f7dac5f9a06bba00bcd5723e
    env_file:
      - .env
    environment:
      - PORT=1111
    network_mode: host
    restart: unless-stopped

