
services:
  server:
    image: ghcr.io/jcollingwood/jc-kotlin-template:b32fbec1f322ef779a62f1496343748422fa463a
    env_file:
      - .env
    environment:
      - PORT=1111
    network_mode: host
    restart: unless-stopped

