
services:
  server:
    image: ghcr.io/jcollingwood/jc-kotlin-template:9f2d1e78ecf061285053ef970baba68628ebfce6
    env_file:
      - .env
    environment:
      - PORT=1111
    network_mode: host
    restart: unless-stopped

