services:
  server:
    image: ghcr.io/jcollingwood/jc-kotlin-template:d165e061cca6d689213a9ba22383fb5e9a81f548
    env_file:
      - .env
    environment:
      - PORT=1111
    network_mode: host
    restart: unless-stopped
    volumes:
      - sqlite_data:/app/db/

volumes:
  sqlite_data:
    driver: local


