services:
  server:
    image: ghcr.io/jcollingwood/jc-kotlin-template:052b2d632d2b8b9df058bdbf3ace156c3aaed666
    env_file:
      - .env
    environment:
      - PORT=1111
    network_mode: host
    restart: unless-stopped
    volumes:
      - sqlite_data:/app/db/

volumes:
  sqlite_data:
    driver: local


