
services:
  server:
    image: ghcr.io/jcollingwood/jc-kotlin-template:14bb0f9c0d3478bc4a550efb77035e61c86fb3d2
    env_file:
      - .env
    environment:
      - PORT=1111
    network_mode: host
    restart: unless-stopped

