services:
  server:
    image: ghcr.io/jcollingwood/jc-kotlin-template:243ff33df7d6386e947afb8523d25f0ad73d0b57
    env_file:
      - .env
    environment:
      - PORT=1111
    network_mode: host
    restart: unless-stopped
    volumes:
      - sqlite_data:/app/db/

volumes:
  sqlite_data:
    driver: local


