
services:
  server:
    image: ghcr.io/jcollingwood/jc-kotlin-template:8252ade76950f787367a7357f150f07dca90a625
    env_file:
      - .env
    environment:
      - PORT=1111
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./db/template_db.db:/app/db/template_db.db


