
services:
  server:
    image: kotlin-template-server:latest
    ports:
      - "3333:3333"
    env_file:
      - local.env
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
