services:
  server:
    image: ghcr.io/jcollingwood/jc-kotlin-template:b0539694b2a4193bdddc4247fc62db39a8cd2e1d
    env_file:
      - .env
    environment:
      - PORT=1111
    network_mode: host
    restart: unless-stopped
    volumes:
      - sqlite_data:/app/db/

volumes:
  sqlite_data:
    driver: local


