services:
  server:
    image: ghcr.io/jcollingwood/jc-kotlin-template:436e0c5e474d3920bf537fa96f570a46be25b2a6
    env_file:
      - .env
    environment:
      - PORT=1111
    network_mode: host
    restart: unless-stopped
    volumes:
      - sqlite_data:/app/db/

volumes:
  sqlite_data:
    driver: local


