version: '3.8'

services:
  server:
    image: kotlin-template-server:latest
    ports:
      - "3333:3333"
    environment:
      - JC_TEMPLATE_GOOGLE_CLIENT_ID=${JC_TEMPLATE_GOOGLE_CLIENT_ID}
      - JC_TEMPLATE_GOOGLE_CLIENT_SECRET=${JC_TEMPLATE_GOOGLE_CLIENT_SECRET}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
