
services:
  server:
    image: ghcr.io/jcollingwood/jc-kotlin-template:d202cdb56d423734119fe106c92f24a1b91f5358
    env_file:
      - .env
    environment:
      - PORT=1111
    network_mode: host
    restart: unless-stopped

