services:
  server:
    image: ghcr.io/jcollingwood/jc-kotlin-template:62c76a5158f5266ab6f3a4bd79df73889071898b
    env_file:
      - .env
    environment:
      - PORT=1111
    network_mode: host
    restart: unless-stopped
    volumes:
      - sqlite_data:/app/db/

volumes:
  sqlite_data:
    driver: local


