services:
  server:
    image: ghcr.io/jcollingwood/jc-kotlin-template:a4688341e528bdbcd96975c5d3bc8a3c56939964
    env_file:
      - .env
    environment:
      - PORT=1111
    network_mode: host
    restart: unless-stopped
    volumes:
      - sqlite_data:/app/db/

volumes:
  sqlite_data:
    driver: local


