
services:
  server:
    image: ghcr.io/jcollingwood/jc-kotlin-template:e5694c8b437ffeff71e619709f693c48a6f09f39
    env_file:
      - .env
    environment:
      - PORT=1111
    network_mode: host
    restart: unless-stopped

