name: Manual Snapshot Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build from'
        required: true
        default: 'main'

jobs:
  gradle-build:
    uses: ./.github/workflows/reusable-gradle-build.yml
    with:
      ref: ${{ github.event.inputs.branch }}

  docker-build-and-push:
    needs: gradle-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Docker Build and Push
        uses: ./.github/workflows/reusable-docker-build.yml
        with:
          ref: ${{ github.event.inputs.branch }}
          push: true
          tag: ghcr.io/${{ github.repository }}:snapshot-${{ github.event.inputs.branch }}-${{ github.sha }}

  echo-tag:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Echo Docker Tag
        run: echo "Docker image tag: ghcr.io/${{ github.repository }}:snapshot-${{ github.event.inputs.branch }}-${{ github.sha }}"
